Set version once, then validate, before running other commands

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -7,8 +7,39 @@ on:
       - "v*.*.*"
 
 jobs:
+  setup-envs:
+    name: Set up the build names and such
+    runs-on: ubuntu-20.04
+    outputs:
+      version: ${{ steps.version.outputs.version }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      - name: Version
+        id: version
+        shell: bash
+        run: |
+          v=${GITHUB_REF##*/}
+          echo "Version: $v"
+          echo "::set-output name=version::$v"
+
+      - name: Check version
+        shell: bash
+        run: |
+          rx='^([0-9]+\.){0,2}(\*|[0-9]+)$'
+          VERSION=${{steps.version.output.version}}
+          if [[ $VERSION =~ $rx ]]; then
+            echo "INFO:<-->Version $VERSION"
+          else
+            echo "ERROR:<->Unable to validate package version: '$VERSION'"
+            exit 1
+          fi
   generate-changelog:
     name: Generate changelog
+    needs: setup-env
     runs-on: ubuntu-20.04
     outputs:
       release_body: ${{ steps.release.outputs.release_body }}
@@ -24,7 +55,7 @@ jobs:
           args: -vv --latest --strip header
         env:
           OUTPUT: CHANGELOG.md
-          
+
       - name: Set the release body
         id: release
         shell: bash
@@ -35,57 +66,10 @@ jobs:
           r="${r//$'\n'/'%0A'}"
           r="${r//$'\r'/'%0D'}"
           echo "::set-output name=release_body::$r"
-  build-python:
-      name: Build python
-      runs-on: ubuntu-20.04
-      steps:
-        - name: Checkout
-          uses: actions/checkout@v2
-        - name: Install dependencies
-          run: |
-            python -m pip install --upgrade pip
-            pip install tox
-        - name: Update version in setup.cfg
-          run: | 
-            sed -i 's/VERSION/${GITHUB_REF:11}/g' setup.cfg
-        - name: Build with tox
-          run: tox -e build
-        - name: Upload artifact
-          uses: actions/upload-artifact@v2
-          with:
-            name: dist
-            path: dist/
 
-  publish-github:
-  
-    name: Publish on GitHub
-    needs: [generate-changelog,build-python]
-    runs-on: ubuntu-20.04
-    
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Set the release version
-        shell: bash
-        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
-      - name: Download artifacts
-        uses: actions/download-artifact@v2
-        with:
-          name: dist
-          path: dist
-        
-      - name: Upload the release
-        uses: svenstaro/upload-release-action@v2
-        with:
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          tag: ${{ github.ref }}
-          file: dist/**
-          file_glob: true
-          release_name: "Release v${{ env.RELEASE_VERSION }}"
-          body: "${{ needs.generate-changelog.outputs.release_body }}"
-          
-  publish-gh-page:
-    name: Publish to Github Pages
+  build-python:
+    name: Build python
+    needs: setup-env
     runs-on: ubuntu-20.04
     steps:
       - name: Checkout
@@ -93,12 +77,57 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install tox 
+          pip install tox
       - name: Update version in setup.cfg
-        run: | 
-          sed -i 's/VERSION/${GITHUB_REF:11}/g' setup.cfg
+        run: |
+          sed -i 's/VERSION/${{needs.setup-envs.outputs.version}}/g' setup.cfg
+      - name: Build with tox
+        run: tox -e build
+      - name: Upload artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: dist
+          path: dist/
+
+  publish-github:
+    name: Publish on GitHub
+    needs: [generate-changelog,build-python, setup-env]
+    runs-on: ubuntu-20.04
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Download artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: dist
+          path: dist
+      - name: Upload the release
+        uses: svenstaro/upload-release-action@v2
+        with:
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          tag: ${{ github.ref }}
+          file: dist/**
+          file_glob: true
+          release_name: "Release v${{needs.setup-envs.outputs.version}}"
+          body: "${{ needs.generate-changelog.outputs.release_body }}"
+
+  publish-gh-page:
+    name: Publish to Github Pages
+    needs: setup-env
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install tox
+      - name: Update version in setup.cfg
+        run: |
+          sed -i 's/VERSION/${{needs.setup-envs.outputs.version}}/g' setup.cfg
       - name: Build docs with tox
-        run: tox -e docs      
+        run: tox -e docs
       - name: Upload the docs
         uses: JamesIves/github-pages-deploy-action@4.1.7
         with:
